sudo: false
language: node_js
node_js: 14.15.3
script:
- npm run audit
- npm run snyk
- npm run lint
- npm run test
after_success: npm run coveralls
env:
  SNYK_TOKEN:
    secure: IhdnusFZXHyD1S3lbYetdJMtlPGwmkL7NYpQUeET0lFkYdad810lNPGbwo4xTsf71ODAprjncn1qnlGhX4WrmA7knXm+f1bix5MRR9gEPPMSOf8d6nBy5xMG5mGL1VhDhF53GUUgl809bzgqb/W86AxDF46E/980SEbnytIPAkQC/Q7TyLgu6EcoL2ITbwB0+e6uoD7MhmqyOw+ewCBxY1bRW0tR3Yj6c2OUiF2l+PUt8YR3Qpzi7ja59zrL9S2/ewAZ4ueeAlWEH/NIXskva6JmqFhZ2+0SfVeYhMSiwVZk5wdlR9mxjSOovf64h1M2Pk0lnslom1ktA3Gvtk1PChnHHYcBCDWIwyAZX51CFKUiDpO78M5RnwElF6w9hWuWcbO6yTi1qNWsLLbAuvPiZoytfPRsQQZqKfJGumraw6GcPFHeHc0549sAciJC+yXE2nrVhkDvs6Nd4jCm1NDGI1Ha6dcqdMnR3BmcpVV6JXVk2LubktJF5Z90lVpH+tIUevU2pEoxT2fy7+/LratDzOpB1WYElgtqEFv3EKBsmq69N893bhnB6fRRroT+MsOQy1+IjB7gJ3/3SDyZCDlhEZ5nYxN/XldnxVXwcyaEj7FtnN1YMtc+ztK556FGzX4ziLgb9fIFYfZNTFYTozT9uQHTy6SvVhbckXcEBDgLD7A=
before_deploy:
- npm run build
deploy:
  provider: npm
  email: adonisv79@gmail.com
  skip_cleanup: true
  api_key:
    secure: An0qsGIlg6vJb/CEIoH+GOqFaS9omSwRqHP7xU4nlPkoAyYibavv85pJBp5ZBzxoB6o7pFuZBgQMvEnsuqf97OBsdxgfHBiggDILrHfoqWS/GYy4GsYDQhgVfk/gMzqTKicW1X3ao4/0cujMv2Nm2dVJzUV1mbCrgNPqcv/H1/AxGZBPPmbVEHpkvsAY3jZFyVAb97JqSmQqvyyfAiG26CAJrDgFpDIFS+8gMcXyyHGXDsOiqI5Drly+IHlHB1wW2p/NZ+GB13yJQXpQyoXj9eAhR+9X2AwgXTE04rogqYUYq0RDz0JKVpuys2rpT5t2BTNNbkW8bNefwLdXYZr18jdp7G2j15RezmTF9XMsOPQJl0MAHCPZ8td810E96T0uchQ/2vCHkPiddII5+oCX0hNXxGS3HfuIqqkF9RL3XfJsZJJ6Bmvb13CIqk6yzFbU34OTjAlEZAIxeRFl41CbYkMx0DwAYW6reqlcpt+XQpTjuPv/NfIM+JI0EYICOOfVaZKfP4K6+qNsVoZJU6QOE8MVj9MW634EqazUyRl6VNXmZPxNBdhlwXK9b8Gn32U/QteCiZeoh9721JSGIALeSS0GifaDdOypaT6SWfnZZunHSRbVlJyAtJX0Uy7jLU90p7L4UxkJQbAO2A5mNxO4dyn5lStDJOQszjs+tL7kiVg=
  on:
    tags: true
    branch: master
