sudo: false
language: node_js
node_js: 14.15.3
script:
- npm run audit
- npm run snyk
- npm run lint
- npm run test
after_success: npm run coveralls
env:
  global:
    secure: QLEsYUkxSoNstoOmkTpw9mHWbxOoUyflxkiy2um7yH98TYWN3LnLfMWYdyGHrUQBwxnbp411TuvjAxYVD246ZCWHOoL+POswAlUVwT6wL7u6qkVI9dvtQ71Phv9QF9mbkxOUCGmnzQdJCQhxFsUQwx53X4OjFw8uv+Kdl0CJUDURLCp5xoQ5zfWK5+KXSBmOFuUovplghy5eRWeOhLxnY4SBHvn/ntYZWNNdWqboQPZjJsp30W0a91ZiV7PnFBwtK5mmcBPgRM1T549OTb4Zc6hgCXKzlse1jnpRqdHOt4hLFjMosYujg/LgkOlYYB8h9F9v5Lwi5tXwUEOQ5Kpd6UnlY0TZ7jg9vLJvcJNM9K22BXEvDcCBatgdtFZYXvqxt2aGLnAspX5k/hLaoelws6nlrVkrAC9MPpReNaQMVG03+G+KRAbyHirqncv36+fKHeC4BKcdF3J9mkk7xqW7C/0nBnvvsGfi6ZRBDq9XB1aouqEtqgcCer3A/4ZWK11FZPx//qrXMQHtN2d52Lys+77Bjs4WO0C7TMY1a119xDokJUkhKupLPtw8wSYzSmg5Ldbc78pGEOmEhDIP1cdz5JvfyM5Spa7p38L3YmAxV4V2pk93fHz3yXy4KMfeejBJOLWnG+qsZ/SPAW/meJpIYFDIwXv5h7kp9m7FQ9KyJ1o=
